---
# Copyright (C) 2015 PSP2SDK Project
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

sudo: required
dist: trusty

before_install:
 - set -e

 - sudo apt-get update -qq -y
 - sudo apt-get install -qq -y gcc-mingw-w64-x86-64 libssl-dev libxml2-dev

 - wget -q https://sourceforge.net/projects/mingw-w64/files/External%20binary%20packages%20%28Win64%20hosted%29/Binaries%20%2864-bit%29/OpenSSL-1.0.0a-bin-x64.zip
 - sudo unzip -qq OpenSSL-1.0.0a-bin-x64.zip x86_64-w64-mingw32/* -d /usr

 - git clone -q --single-branch -b v2.9.2 https://git.gnome.org/browse/libxml2
 - cd libxml2
 - ./autogen.sh -q --host=x86_64-w64-mingw32 --prefix=/usr/x86_64-w64-mingw32 --without-lzma --without-python
 - sudo make install -j4
 - cd ..

 - git clone -q "https://$TOKEN@github.com/psp2sdk/psp2sdk.git" $DIST | sed s/$TOKEN/\${TOKEN}/g

script:
 - export REV=$(git describe --always)
 - git -C $DIST config user.name "Travis CI"
 - git -C $DIST config user.email contact@travis-ci.com

 - aclocal
 - automake --add-missing
 - autoconf

 - git -C $DIST checkout amd64-pc-linux-gnu
 - git -C $DIST rm -qrf psp2sdk
 - ./configure $FLAGS CFLAGS=-I/usr/include/libxml2
 - make install -j4
 - make clean
 - git -C $DIST add -f psp2sdk
 - git -C $DIST commit -qam "tools $REV"

 - git -C $DIST checkout x86_64-w64-mingw32
 - git -C $DIST rm -qrf psp2sdk
 - ./configure $FLAGS --host=x86_64-w64-mingw32 CFLAGS=-I/usr/x86_64-w64-mingw32/include/libxml2
 - make install -j4
 - cp /usr/x86_64-w64-mingw32/bin/libxml2-2.dll $PREFIX/bin
 - git -C $DIST add -f psp2sdk
 - git -C $DIST commit -qam "tools $REV"

after_success:
 - git -C $DIST push -q origin | sed s/$TOKEN/\${TOKEN}/g

env:
 global:
  - DIST="$PWD/dist"
  - PREFIX="$DIST/psp2sdk"
  - FLAGS="-q --prefix=$PREFIX"
  - secure: "V1D3N6iGEat/Gt7iBclpSHrve28gqdxspZPXQfJXIksXWpT/2tTU5sIeltnHelgumpP1uQWNOuknoN4UVDzc7tuK3glq9LFKDXGERY1FT48MtmadjXrcg684Unz+G70Pmgidhvs3qQCKsWmE1l1ZP+ghPQEH0424Rl6a5099eyTwDen8jdDJ65Kaj+RqQGsM3Hhr0mGbVz/lYh3pFiwK50h94yymLIxhtrRA3ccXCYzzpoYpveofrBQ1rd2b/t9ODMNikr48fXJ6xD9s0XgS8wMByvVh+jxuyz8V27+AxCHZXBs9snBulCY8r8iFDS+9705yClIHiZNFgH2XuBPIZ7l66Yp4WfCjegmJWZ3zeJRkuHEiANZF1XWAaznLCnskiBZNtkCjw7Tcm7amW+ES93T+lEMX2mVFzzYAkJr6BKjgo8vkvN6+tO34Rc3DzJA4QN4so/0UyTHi1HkeMNR2GKI2nHU+5LDubxJALlk3D1fP/U+7i8Pj7q0o6Qumv5mMc2y+GqUqteU8+oVIxqkRa1cz6ftFI92Ak0yS7qtgD0KbXo0NcpbqjEM2RzulHXvAlYuv88XZplUwkyycXh3jt3Jz0whCtpP9pbYSr32xFUZ9C53GaA9gfAG7PCsOGhEsshsdYw1mq7PwMvWw79LFBAl6kV8kayCXFs+f8QXVVR8="
